export default {
  "login": "calvinucheoma",
  "id": 76457560,
  "node_id": "MDQ6VXNlcjc2NDU3NTYw",
  "avatar_url": "https://avatars.githubusercontent.com/u/76457560?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/calvinucheoma",
  "html_url": "https://github.com/calvinucheoma",
  "followers_url": "https://api.github.com/users/calvinucheoma/followers",
  "following_url": "https://api.github.com/users/calvinucheoma/following{/other_user}",
  "gists_url": "https://api.github.com/users/calvinucheoma/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/calvinucheoma/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/calvinucheoma/subscriptions",
  "organizations_url": "https://api.github.com/users/calvinucheoma/orgs",
  "repos_url": "https://api.github.com/users/calvinucheoma/repos",
  "events_url": "https://api.github.com/users/calvinucheoma/events{/privacy}",
  "received_events_url": "https://api.github.com/users/calvinucheoma/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Calvin",
  "company": null,
  "blog": "https://chukwuma-ucheoma-portfolio.netlify.app",
  "location": "Nigeria",
  "email": null,
  "hireable": true,
  "bio": "Web developer",
  "twitter_username": "_chukss__",
  "public_repos": 70,
  "public_gists": 0,
  "followers": 1,
  "following": 3,
  "created_at": "2020-12-22T00:07:02Z",
  "updated_at": "2022-10-26T02:18:10Z"
}